### ISSUE TITLE
Table: Таблица должна ложиться под любой фон

### ISSUE THREAD

**Issue by stug111** [gazprom-neft/consta-uikit#509]
Сейчас есть проблема с тем что  нет возможности изменить цвет подложки для таблицы.
Приходятся использовать что-то вроде
```css
.table {
  --color-bg-default: var(--color-bg-secondary);
}
```

Хотелось бы чтобы была возможность либо указывать цвет подложки через пропсы, либо подложка таблицы была прозрачной
