### ISSUE TITLE
Theme: задать переменные для ширины шрифта

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#742]
при подключении своего шрифта возможно потребуется переназначить значения ширины у текста 
сейчас так 

```css
&_weight {
    &_thin {
      font-weight: 100;
    }

    &_light {
      font-weight: 300;
    }

    &_regular {
      font-weight: normal;
    }

    &_semibold {
      font-weight: 600;
    }

    &_bold {
      font-weight: bold;
    }

    &_black {
      font-weight: 900;
    }
  }
```

и чтобы переопределить приходится в своей теме указывать для каждого модификатора каждого компонента значения, что кажется не явным и не удобным

```css
.Theme_font_gpnPromo {
  --font-primary: 'Inter', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', 'Roboto', sans-serif;
  --font-mono: source-code-pro, Menlo, Monaco, Consolas, 'Courier New', monospace;
  font-family: var(--font-primary);

  .Text_weight_bold {
    font-weight: 800;
  }
}
```

если вынесим эти значения в переменные темы то такой проблемы не будет
